#!/usr/bin/env python3
"""
sim_isa.py -- run an assembled binary on the real network and image.

Usage:
    python sim_isa.py [instr.mem] [data.mem] [--packer FILE] [--regen] [--mhz N]

    E.g
    python sim_isa.py instruction_mac4.mem data_mac4.mem dnn_parameters_final.txt mnist_image.mem --packer pack_data_mem_v3.py

Defaults:
    instr.mem  instruction_mac4.mem
    data.mem   data_mac4.mem
    --packer   pack_data_mem_v3.py
    --mhz      50          (the core runs on clk/2)

FIXED (this cost a Vivado run):
  * The packer module was HARDCODED to pack_data_mem_v2.py while the MAC4
    build needs v3. Worse, this script REGENERATED the .mem file before
    running, so pointing it at a v3-generated data_mac4.mem silently
    overwrote it with the v2 layout (28509 words, result word 28508) and
    then executed the MAC4 binary against it. Result: garbage logits.
  * Regeneration is now OFF by default. The existing .mem file is read as-is
    and its length is checked against what the packer expects. Use --regen
    only when you deliberately want to rebuild it.
  * The clock rate is no longer hardcoded to 100 MHz.

RULE OF THUMB: only pack_data_mem_v*.py may write a .mem file. Nothing else.
"""
import sys
import numpy as np
import importlib.util
from isa_sim_core import run, load_mem, check, s32

args = [a for a in sys.argv[1:] if not a.startswith("--")]
flags = [a for a in sys.argv[1:] if a.startswith("--")]

def flagval(name, default):
    for i, f in enumerate(flags):
        if f.startswith(name + "="):
            return f.split("=", 1)[1]
    return default

imem    = args[0] if len(args) > 0 else "instruction_mac4.mem"
dmem    = args[1] if len(args) > 1 else "data_mac4.mem"
params  = args[2] if len(args) > 2 else "dnn_parameters_final.txt"
image   = args[3] if len(args) > 3 else "mnist_image.mem"
packer  = flagval("--packer", "pack_data_mem_v3.py")
mhz     = float(flagval("--mhz", "50"))
regen   = "--regen" in flags

spec = importlib.util.spec_from_file_location("p", packer)
p = importlib.util.module_from_spec(spec)
spec.loader.exec_module(p)
print(f"packer   : {packer}")
print(f"binary   : {imem}")
print(f"data     : {dmem}{'  (REGENERATING)' if regen else '  (reading as-is)'}")

W, B = p.parse_dnn_parameters(params)
xq = p.load_image(image, 127.0, verbose=False)

# Compute the expected layout WITHOUT writing, unless --regen was given.
cal = p.generate(W, B, xq, 127.0, dmem if regen else "_expected_layout.tmp",
                 verbose=False)
print(f"layout   : {cal['total_words']} words, result word {cal['result_word']}")

mem = load_mem(dmem)
actual = sum(1 for l in open(dmem) if l.strip())
if actual != cal['total_words']:
    print(f"\n*** LAYOUT MISMATCH ***")
    print(f"{dmem} has {actual} words but {packer} expects {cal['total_words']}.")
    print(f"The .mem file was generated by a different packer version.")
    print(f"Fix:  python {packer} {params} {dmem} {image} 127.0")
    sys.exit(2)

steps, R = run(imem, mem)
gold = [int(v) for v in p.golden_model(cal, xq, verbose=False)]
hw, arg, ok = check(cal, mem, gold, cal['result_word'])
flt = p.float_model(W, B, np.asarray(xq, dtype=np.float64) / 127.0)

print(f"\ninstructions {steps:,}   cycles@CPI3 {steps*3:,}   "
      f"@{mhz:.0f}MHz {steps*3/(mhz*1e6)*1000:.2f} ms")
print("hw     :", hw)
print("golden :", gold)
print("float  :", np.array2string(flt, precision=2))
print(f"\nhw argmax {arg}   golden {int(np.argmax(gold))}   float {int(np.argmax(flt))}")
try:
    label = open("mnist_label.txt").read().strip()
    print(f"true label {label}   -> {'CORRECT' if str(arg) == label else 'WRONG'}")
except FileNotFoundError:
    pass
print("\nMATCH" if ok else "\nMISMATCH")
sys.exit(0 if ok else 1)